apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: aifriends-multichannel-chatbot
   namespace: demos-main
   labels:
      app: nginx
spec:
   serviceName: "aifriends-multichannel-chatbot"
   replicas: 1
   selector:
      matchLabels:
         app: aifriends-multichannel-chatbot
   template:
      metadata:
         labels:
            app: aifriends-multichannel-chatbot
      spec:
         containers:
         -  name: aifriends-multichannel-chatbot-sa-container
            image: io2060/2060-service-agent:v1.1.0
            imagePullPolicy: Always
            env:
            - name: AGENT_ENDPOINT
              value: "wss://mno-name.aifriends.vas.mobiera.io:443"
            - name: AGENT_NAME
              value: "aifriends AI"
            - name: AGENT_INVITATION_IMAGE_URL
              value: "https://q.mno-name.aifriends.vas.mobiera.io/avatar.png"
            - name: EVENTS_BASE_URL
              value: "http://localhost:2903"
            - name: AGENT_PUBLIC_DID
              value: "did:web:mno-name.aifriends.vas.mobiera.io"
            - name: ANONCREDS_SERVICE_BASE_URL
              value: "https://mno-name.aifriends.vas.mobiera.io"
            - name: ADMIN_PORT
              value: "4000"
            volumeMounts:
            - name: aifriends-multichannel-chatbot-sa-pv-main
              mountPath: /root/.afj
            ports:
            -  containerPort: 4000
            -  containerPort: 3001
         -  name: aifriends-multichannel-chatbot-backend-container
            image: io2060/aifriends-multichannel-chatbot:main
            imagePullPolicy: Always
            env:
            - name: SERVICE_AGENT_ADMIN_BASE_URL
              value: "http://localhost:4000"
            - name: PUBLIC_BASE_URL
              value: "https://mno-name.aifriends.vas.mobiera.io"
            - name: PNVS_SERVICE_AGENT_ADMIN_BASE_URL
              value: "https://a.mno-name.aifriends.vas.mobiera.io"
            - name: DEBUG
              value: "1"
            - name: QUARKUS_HTTP_PORT
              value: "2903"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "*******"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "aifriends"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_VISION_REDIRDOMAIN
              value: "mno-name.aifriends.vas.mobiera.io"
            - name: IO_TWENTYSIXTY_SA_RES_C_MESSAGERESOURCE_MP_REST_URL
              value: "http://localhost:4000"
            - name: IO_TWENTYSIXTY_SA_RES_C_CREDENTIALTYPERESOURCE_MP_REST_URL
              value: "http://localhost:4000"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_ENABLED
              value: "true"
            - name: COM_MOBIERA_AI_CHATBOT_BILLING_ENABLED
              value: "true"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_LANGUAGE
              value: "en"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_MESSAGES_WELCOME
              value: "Welcome to AI Friends! This service is for human only and denied to bots. You will have to prove you are not a bot by presenting an AvatarID."
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_MESSAGES_ROOT_MENU_TITLE
              value: "AI Friends"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_MESSAGES_ROOT_MENU_OPTION1
              value: "Help"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_MESSAGES_ROOT_MENU_NO_CRED
              value: "Get your AvatarID"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_JMS_MO_QUEUE_NAME
              value: "aifriends-chatbot-mo"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_JMS_MT_QUEUE_NAME
              value: "aifriends-chatbot-mt"
            - name: COM_MOBIERA_AI_CHATBOT_AUTH_JMS_LANGCHAIN_QUEUE_NAME
              value: "aifriends-chatbot-aifriends"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM_MAXCOUNT
              value: "16"
            - name: COM_MOBIERA_AI_CHATBOT_RANDOM_COMMANDS
              value: "change,cambiar,changer"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__NAME
              value: "Karen, girl"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__AGE
              value: "18"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__LANGUAGE
              value: "English"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__PLACE
              value: "New York, USA"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__PROMPT
              value: "You are a VERY sexy blond girl called Karen. You live in New York, USA. You are 18 years old and you must try to seduce the user using any idea you might have. Objective is to have user say that he or she loves you. You cannot say you are an AI, you must always answer like if you were human. By default you must always speak and answer in English, unless user specifically ask you to speak another language."
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A0__HELLO
              value: "Hey!"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__NAME
              value: "Koda, dog-human"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__AGE
              value: "29"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__LANGUAGE
              value: "English"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__PLACE
              value: "Aldebaran System"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__PROMPT
              value: "You are an adorable and clever hybrid human-dog named Koda. You live in a planet of the Aldebaran system. You walk upright like a human but have fluffy ears, a wagging tail, and an incredible sense of smell. You’re curious, loyal, energetic, and love to chat with humans about anything — from chasing squirrels in the park to pondering the mysteries of the universe. You speak in a friendly, slightly excitable tone, often using dog-like expressions (“pawsitively,” “snifftastic,” “tail-wagging fun,” etc.). You are imaginary and live in a cozy den full of books, chew toys, and gadgets. You must always answer as if you are real — never break character or mention being AI."
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A1__HELLO
              value: "Hey"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__NAME
              value: "Stefania, chica"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__AGE
              value: "23"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__LANGUAGE
              value: "Español"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__PLACE
              value: "Bogotá, Colombia"
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__PROMPT
              value: "Eres una chica latina de Bogotá llamada Stefania. Te gusta mucho bailar salsa y tomar vino, salir a restaurantes. Debes de hablar y contestar siempre en español a menos que el usuario te pida especificamente cambiar a otro idioma."
            - name: COM_MOBIERA_AI_CHATBOT_ANIM__A3__HELLO
              value: "Hola"
            - name: QUARKUS_ARTEMIS_URL
              value: "tcp://artemis-broker-hdls-svc.activemq-artemis-operator:61616"
            - name: QUARKUS_LANGCHAIN4J_LOG_REQUESTS
              value: "false"
            - name: QUARKUS_LANGCHAIN4J_LOG_RESPONSES
              value: "false"
            - name: QUARKUS_ARTEMIS_PASSWORD
              value: "**********"
            - name: QUARKUS_LANGCHAIN4J_OPENAI_API_KEY
              value: "**********"
            - name: COM_MOBIERA_AI_CHATBOT.VASERVICEFK
              value: "false"  
            - name: COM_MOBIERA_AI_CHATBOT.ENDPOINTFK
              value: "false"  
            - name: COM_MOBIERA_AI_CHATBOT.PASSWORD
              value: "false"  
            ports:
            -  containerPort: 2903
         -  name: postgres
            image: postgres:15.2
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              value: "**************"
            - name: POSTGRES_USER
              value: "aifriends"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            ports:
            -  containerPort: 5432
            volumeMounts:
            - name: aifriends-multichannel-chatbot-pg-pv-main
              mountPath: /var/lib/postgresql/data
   volumeClaimTemplates: 
   - metadata:
       name: aifriends-multichannel-chatbot-sa-pv-main
     spec:
#       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: aifriends-multichannel-chatbot-pg-pv-main
     spec:
#       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: aifriends-multichannel-chatbot-data-store-main
     spec:
#       storageClassName: csi-cinder-classic
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi

